# Host utilities; runtime versions belong in mise.toml.
brew "git"
brew "gh"
brew "tmux"
brew "ripgrep"
brew "jq"
brew "uv"
brew "mise"
brew "fd"
brew "yq"
brew "shellcheck"
brew "shfmt"
brew "yamllint"
brew "git-lfs"
brew "poppler"
brew "ffmpeg"
brew "imagemagick"
brew "pandoc"
brew "gitleaks"
brew "trivy"
brew "rclone"
brew "pkgconf"
brew "doppler"

# Keepresso is distributed through its maintainer's tap.
tap "gyorgysh/keepresso"

# Authentication and macOS permissions are manual.
cask "1password"
cask "1password-cli"
cask "google-chrome"
cask "tailscale-app"
cask "chatgpt"
cask "spotify"
cask "ghostty"
cask "gyorgysh/keepresso/keepresso"
