# Host utilities; runtime versions belong in mise.toml.
brew "git"
brew "gh"
brew "ripgrep"
brew "jq"
brew "uv"
brew "mise"
brew "fd"
brew "yq"
brew "shellcheck"
brew "shfmt"
brew "yamllint"
brew "git-lfs"
brew "poppler"
brew "ffmpeg"
brew "imagemagick"
brew "pandoc"
brew "gitleaks"
brew "trivy"
brew "rclone"
brew "pkgconf"
brew "doppler"

# Authentication and macOS permissions are manual.
cask "1password"
cask "1password-cli"
cask "google-chrome"
cask "tailscale-app"
cask "chatgpt"
cask "spotify"
cask "ghostty"

# Amphetamine: Mac App Store, after App Store sign-in.
